In [1]:
import numpy as np

In [2]:
import random

# Creación y Indexación

In [4]:
# 1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

array_1d = np.random.randint(10, 100, size = (50))
array_1d

array([73, 88, 96, 76, 29, 62, 76, 55, 44, 26, 70, 64, 92, 37, 97, 64, 99,
       71, 88, 40, 58, 86, 38, 24, 41, 38, 21, 70, 50, 22, 89, 43, 32, 86,
       48, 97, 58, 52, 93, 30, 22, 44, 83, 11, 75, 79, 47, 21, 99, 93],
      dtype=int32)

In [6]:
multiplos_5 = array_1d[array_1d %5 == 0]
multiplos_5

array([55, 70, 40, 70, 50, 30, 75], dtype=int32)

In [7]:
# 2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). 
# Utiliza indexación para obtener los elementos en las posiciones impares.

array_1d_2 = np.random.randint(1, 21, size = (30))
array_1d_2

array([17, 11, 15, 11, 18,  9,  5, 15,  6,  3, 10, 14,  6, 17,  5, 17,  6,
        8,  6,  2,  5,  2, 12, 14, 18, 14,  6, 12, 19, 14], dtype=int32)

In [8]:
array_1d_2[1::2]

array([11, 11,  9, 15,  3, 14, 17, 17,  8,  2,  2, 14, 14, 12, 14],
      dtype=int32)

In [ ]:
# 3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1)

In [13]:
array_2d = np.random.uniform(10, 50, size = (4, 6))
array_2d

array([[23.6776558 , 13.74272544, 39.00505554, 35.52671151, 36.03207684,
        24.89897245],
       [16.15819765, 25.71720564, 19.80223163, 30.26441591, 32.28029032,
        39.00590796],
       [37.70062953, 11.10509001, 28.94921686, 47.07848344, 47.8200022 ,
        29.66560452],
       [31.56931831, 16.71286257, 32.67642447, 18.17334658, 14.82306988,
        20.09386157]])

In [14]:
array_2d.ndim

2

In [15]:
# 3.1.  Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales

redondeado = np.round(array_2d[-1], 2)
redondeado

array([31.57, 16.71, 32.68, 18.17, 14.82, 20.09])

In [30]:
# BONUS # 
# 4. Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). 
# Reemplaza los elementos en posiciones múltiplos de 3 por 0.

array_3d = np.random.randint(0, 101, (2, 3, 5))
array_3d

array([[[ 14,  57,  26,  58,  61],
        [ 74,  34,  14,  50,  89],
        [ 14,  96,  23,  87,  90]],

       [[ 76,  92,  18,  63, 100],
        [ 70,  59,  24,  29,  59],
        [ 27,   8,  94,  51,  59]]], dtype=int32)

In [32]:
mask = array_3d % 3 == 0
mask

array([[[False,  True, False, False, False],
        [False, False, False, False, False],
        [False,  True, False,  True,  True]],

       [[False, False,  True,  True, False],
        [False, False,  True, False, False],
        [ True, False, False,  True, False]]])

In [34]:
array_3d[mask] = 0
array_3d

array([[[ 14,   0,  26,  58,  61],
        [ 74,  34,  14,  50,  89],
        [ 14,   0,  23,   0,   0]],

       [[ 76,  92,   0,   0, 100],
        [ 70,  59,   0,  29,  59],
        [  0,   8,  94,   0,  59]]], dtype=int32)

# Reshape y Transpose

In [ ]:
# 1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). 
# Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [38]:
tridimensional = np.random.randint(1, 101, size = (2, 3, 4))
tridimensional

array([[[55, 13, 12,  2],
        [40, 75, 60, 19],
        [55, 29, 85, 27]],

       [[67, 50, 47, 51],
        [82, 86, 72, 26],
        [15, 36, 44, 83]]], dtype=int32)

In [43]:
# Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

cambio_dimension = np.reshape(tridimensional, (4, 6))
cambio_dimension

array([[55, 13, 12,  2, 40, 75],
       [60, 19, 55, 29, 85, 27],
       [67, 50, 47, 51, 82, 86],
       [72, 26, 15, 36, 44, 83]], dtype=int32)

In [ ]:
# 2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). 
# Utiliza reshape para convertirlo en un array 2D