In [1]:
import numpy as np

In [2]:
import random

# Creación y Indexación

In [3]:
# 1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

array_1d = np.random.randint(10, 100, size = (50))
array_1d

array([74, 57, 64, 21, 64, 58, 17, 28, 76, 39, 42, 52, 50, 86, 32, 30, 42,
       75, 76, 93, 91, 77, 62, 65, 10, 97, 79, 88, 89, 50, 29, 72, 30, 61,
       83, 76, 78, 79, 12, 28, 59, 14, 38, 60, 30, 76, 54, 78, 24, 19],
      dtype=int32)

In [4]:
multiplos_5 = array_1d[array_1d %5 == 0]
multiplos_5

array([50, 30, 75, 65, 10, 50, 30, 60, 30], dtype=int32)

In [5]:
# 2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). 
# Utiliza indexación para obtener los elementos en las posiciones impares.

array_1d_2 = np.random.randint(1, 21, size = (30))
array_1d_2

array([20,  5,  8,  6, 20, 19, 20,  1, 18,  6, 17,  2,  5,  1, 20,  1, 15,
        3, 17,  4, 16,  4,  7, 17, 10,  9, 17,  7, 15, 16], dtype=int32)

In [6]:
array_1d_2[1::2]

array([ 5,  6, 19,  1,  6,  2,  1,  1,  3,  4,  4, 17,  9,  7, 16],
      dtype=int32)

In [7]:
# 3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1)

In [8]:
array_2d = np.random.uniform(10, 50, size = (4, 6))
array_2d

array([[23.32144662, 29.72763175, 45.07732403, 37.82161752, 48.13356034,
        41.87543027],
       [41.76103622, 30.70811549, 27.8662866 , 10.59795174, 16.3518171 ,
        43.62737567],
       [43.36781704, 29.74486728, 43.45823389, 36.41307828, 39.76339768,
        13.85231315],
       [32.21587466, 33.40769254, 10.09053487, 24.81476239, 13.54314995,
        32.78243546]])

In [9]:
array_2d.ndim

2

In [10]:
# 3.1.  Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales

redondeado = np.round(array_2d[-1], 2)
redondeado

array([32.22, 33.41, 10.09, 24.81, 13.54, 32.78])

In [11]:
# BONUS # 
# 4. Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). 
# Reemplaza los elementos en posiciones múltiplos de 3 por 0.

array_3d = np.random.randint(0, 101, (2, 3, 5))
array_3d

array([[[51, 44, 52, 65, 70],
        [30, 91, 15, 18, 50],
        [63, 14, 59, 65, 50]],

       [[91, 10, 66,  2, 81],
        [40, 73, 79, 24, 69],
        [80, 19, 98, 44, 84]]], dtype=int32)

In [12]:
mask = array_3d % 3 == 0
mask

array([[[ True, False, False, False, False],
        [ True, False,  True,  True, False],
        [ True, False, False, False, False]],

       [[False, False,  True, False,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True]]])

In [13]:
array_3d[mask] = 0
array_3d

array([[[ 0, 44, 52, 65, 70],
        [ 0, 91,  0,  0, 50],
        [ 0, 14, 59, 65, 50]],

       [[91, 10,  0,  2,  0],
        [40, 73, 79,  0,  0],
        [80, 19, 98, 44,  0]]], dtype=int32)

# Reshape y Transpose

In [14]:
# 1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). 
# Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [15]:
tridimensional = np.random.randint(1, 101, size = (2, 3, 4))
tridimensional

array([[[52, 16, 10,  3],
        [56, 74, 56, 79],
        [26,  6, 36, 47]],

       [[30, 73, 41, 94],
        [64, 80, 59, 99],
        [73, 35, 86, 29]]], dtype=int32)

In [16]:
# Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

cambio_dimension = np.reshape(tridimensional, (4, 6))
cambio_dimension

array([[52, 16, 10,  3, 56, 74],
       [56, 79, 26,  6, 36, 47],
       [30, 73, 41, 94, 64, 80],
       [59, 99, 73, 35, 86, 29]], dtype=int32)

In [17]:
# 2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). 
# Utiliza reshape para convertirlo en un array 2D

In [18]:
tridimensional2 = np.random.randint(2, 61, (3, 4, 5))
tridimensional2

array([[[57, 47,  9, 35, 44],
        [20, 49,  3, 35, 17],
        [49, 50, 44, 18, 30],
        [37, 26, 48, 57, 37]],

       [[28,  6, 52, 27, 47],
        [46, 17, 30,  3, 20],
        [27, 34, 58, 23, 10],
        [19, 30, 13, 59, 29]],

       [[23, 56,  9, 36, 18],
        [47, 31, 47,  9,  4],
        [26,  2, 29, 12, 35],
        [28, 17, 36, 19, 46]]], dtype=int32)

In [19]:
cambio_2d = np.reshape(tridimensional2, (12, 5))
cambio_2d

array([[57, 47,  9, 35, 44],
       [20, 49,  3, 35, 17],
       [49, 50, 44, 18, 30],
       [37, 26, 48, 57, 37],
       [28,  6, 52, 27, 47],
       [46, 17, 30,  3, 20],
       [27, 34, 58, 23, 10],
       [19, 30, 13, 59, 29],
       [23, 56,  9, 36, 18],
       [47, 31, 47,  9,  4],
       [26,  2, 29, 12, 35],
       [28, 17, 36, 19, 46]], dtype=int32)

In [20]:
# 3. Utiliza el array 3D del ejercicio 2 de reshape. 
# Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [21]:
con_transpose = tridimensional2.transpose(2, 1, 0)
con_transpose


array([[[57, 28, 23],
        [20, 46, 47],
        [49, 27, 26],
        [37, 19, 28]],

       [[47,  6, 56],
        [49, 17, 31],
        [50, 34,  2],
        [26, 30, 17]],

       [[ 9, 52,  9],
        [ 3, 30, 47],
        [44, 58, 29],
        [48, 13, 36]],

       [[35, 27, 36],
        [35,  3,  9],
        [18, 23, 12],
        [57, 59, 19]],

       [[44, 47, 18],
        [17, 20,  4],
        [30, 10, 35],
        [37, 29, 46]]], dtype=int32)

In [22]:
# 4. Utiliza el array 3D del ejercicio 2 de reshape. 
# Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

In [23]:
cambio_2 = tridimensional2.transpose(0, 2, 1)
cambio_2

array([[[57, 20, 49, 37],
        [47, 49, 50, 26],
        [ 9,  3, 44, 48],
        [35, 35, 18, 57],
        [44, 17, 30, 37]],

       [[28, 46, 27, 19],
        [ 6, 17, 34, 30],
        [52, 30, 58, 13],
        [27,  3, 23, 59],
        [47, 20, 10, 29]],

       [[23, 47, 26, 28],
        [56, 31,  2, 17],
        [ 9, 47, 29, 36],
        [36,  9, 12, 19],
        [18,  4, 35, 46]]], dtype=int32)

# Preguntas teóricas

In [24]:
# 5. ¿Qué diferencia existe entre el reshape y el transpose?

In [25]:
# 6. ¿Y entre el transpose y el swapaxes?


# Funciones Aritméticas y Estadísticas

In [26]:
# 1.Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [27]:
array_3d = np.round(np.random.uniform(0, 1, (2, 3, 5)), 1)
array_3d

array([[[0.2, 0.4, 0.5, 1. , 0.6],
        [0. , 0.7, 0.3, 0.8, 0.2],
        [0.5, 0.9, 0.9, 1. , 0. ]],

       [[0.6, 0.6, 0.8, 0.9, 0.4],
        [0.7, 0.9, 0.1, 0.1, 0.6],
        [0.1, 1. , 0.8, 1. , 0.1]]])

In [28]:
# 2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. 
# Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array 
# bajo las siguientes condiciones:

In [41]:
array_vacio = np.empty((2, 3, 5))
array_vacio


array([[[1.00286629e-311, 1.02765654e-321, 0.00000000e+000,
         0.00000000e+000, 7.56587583e-307],
        [5.02034658e+175, 8.69524087e-071, 1.43643440e-071,
         4.35381930e-061, 1.82712122e+184],
        [1.03985463e-071, 8.06864109e-144, 3.59751658e+252,
         3.96046095e+246, 1.04918621e-153]],

       [[7.69165785e+218, 5.04621343e+180, 1.04917822e-153,
         9.08366793e+223, 8.69524087e-071],
        [1.43643440e-071, 4.35381930e-061, 1.82712122e+184,
         1.04917821e-153, 1.94918966e-153],
        [9.72159846e-072, 9.71521171e-067, 5.64579440e-038,
         2.59027896e-144, 7.79952704e-143]]])

In [ ]:
# Si el valor del array es igual que la media, se reemplaza por "A".
# Si el valor del array es mayor que la media, se reemplaza por "B".
# Si el valor del array es menor que la media, se reemplaza por "C"
# Si el valor es igual que el máximo, se reemplaza por "D"
# Si el valor es igual que el mínimo, se reemplaza por "E".

In [45]:
array_vacio = array_vacio.astype(object)

In [43]:
media = np.mean(array_vacio)
valor_maximo = np.max(array_vacio)
valor_minimo = np.min(array_vacio)

In [48]:
# Reemplazar los valores según las condiciones dadas'
array_vacio[array_vacio == valor_maximo] = "D"  # Igual al máximo -> 'D'
array_vacio[array_vacio == valor_minimo] = "E"  # Igual al mínimo -> 'E'

In [51]:
array_vacio

array([[[1.002866290275e-311, 1.03e-321, 'E', 'E',
         7.565875834485345e-307],
        [5.020346578198683e+175, 8.695240869001642e-71,
         1.4364343974060892e-71, 4.3538192975382835e-61,
         1.827121218059869e+184],
        [1.0398546283683394e-71, 8.068641086557318e-144, 'B',
         3.960460952352905e+246, 1.049186205850693e-153]],

       [[7.691657851623983e+218, 5.046213426914492e+180,
         1.0491782215367351e-153, 9.083667925815433e+223,
         8.695240869001642e-71],
        [1.4364343974060892e-71, 4.3538192975382835e-61,
         1.827121218059869e+184, 1.0491782055759443e-153,
         1.949189659567389e-153],
        [9.72159845687573e-72, 9.715211707824917e-67,
         5.645794399171466e-38, 2.5902789598839934e-144,
         7.799527044147088e-143]]], dtype=object)

In [ ]:
array_vacio[array_vacio == media] = "A"         # Igual a la media -> 'A'
array_vacio[array_vacio > media] = "B"          # Mayor que la media -> 'B'
array_vacio[array_vacio < media] = "C"          # Menor que la media -> 'C'