In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1. ¿Qué diferencia hay entre una Serie y un DataFrame?

In [3]:
# 2. Momento de trabajar con Series. Contesta a las siguientes preguntas:
# Crea dos listas
# Una que se llame "valores" que tenga 7 números aleatorios.
# Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [11]:
valores = np.random.randint(1, 51, size=7)
indices = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']

In [12]:
valores

array([18, 18, 15, 22,  4, 41, 45], dtype=int32)

In [6]:
# A partir de estas dos listas crea una Serie donde la variable 
# "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [13]:
serie = pd.Series(valores, index=indices)
serie

Lunes        18
Martes       18
Miércoles    15
Jueves       22
Viernes       4
Sábado       41
Domingo      45
dtype: int32

In [ ]:
# A partir de las dos listas anteriores crea un diccionario usando un bucle for. 
# Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. 
# Más informción sobre este método aquí.

In [14]:
dicc = {}
for indice, valor, in zip(indices, valores):
    dicc[indice] = valor
print(dicc)

{'Lunes': np.int32(18), 'Martes': np.int32(18), 'Miércoles': np.int32(15), 'Jueves': np.int32(22), 'Viernes': np.int32(4), 'Sábado': np.int32(41), 'Domingo': np.int32(45)}


In [ ]:
# Crea una Serie con el diccionario creado en el punto anterior

In [15]:
serie_dicc = pd.Series(dicc)
print(serie_dicc)

Lunes        18
Martes       18
Miércoles    15
Jueves       22
Viernes       4
Sábado       41
Domingo      45
dtype: int32


In [16]:
# ¿Qué forma tiene esta última Serie?
serie_dicc.shape

(7,)

In [18]:
# ¿Qué tipo de datos tiene?
serie_dicc.dtype

dtype('int32')

In [19]:
# ¿Qué tamaño tiene?
serie_dicc.size

7

In [21]:
# ¿Cuáles son los índices de la Serie?
serie_dicc.index

Index(['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado',
       'Domingo'],
      dtype='object')

In [22]:
# ¿Y los values?
serie_dicc.values

array([18, 18, 15, 22,  4, 41, 45], dtype=int32)

In [23]:
# Extrae el valor para el índice "lunes"
valor_lunes = serie_dicc.loc["Lunes"]
valor_lunes

np.int32(18)

In [30]:
# Extrae el valor para el índice "lunes", "martes" y "miércoles".
valor_l_m_x = serie_dicc.loc[["Lunes", "Martes", "Miércoles"]]
valor_l_m_x

Lunes        18
Martes       18
Miércoles    15
dtype: int32

In [32]:
# Extrae el valor para el índice "lunes" y "domingo".
valor_l_d = serie_dicc.loc[["Lunes", "Domingo"]]
valor_l_d

Lunes      18
Domingo    45
dtype: int32

In [33]:
# 3. Es el turno de los DataFrames

# Crea un array de dos dimensiones con 4 filas y 3 columnas.
array_2d = np.random.randint(1, 51, (4,3))
array_2d

array([[43, 14, 38],
       [14, 20,  2],
       [33, 19, 11],
       [27, 17,  4]], dtype=int32)

In [35]:
# Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".
df = pd.DataFrame(array_2d, columns=["España", "Francia", "Italia"])
df

España  Francia  Italia
0      43       14      38
1      14       20       2
2      33       19      11
3      27       17       4

In [37]:
# Descarga el archivo "medallas" y carga el DataFrame.
medallas = pd.read_csv("medallas.csv")
medallas

Unnamed: 0             País   Oro  Plata  Bronce
0           1            China  1473    994     720
1           2            Japón  1032   1037     985
2           3    Corea del Sur   745    663     827
3           4             Irán   179    181     197
4           5       Kazajistán   155    158     224
5           6            India   154    202     315
6           7        Tailandia   132    175     278
7           8        Indonesia   112    131     240
8           9     China Taipéi    99    144     276
9          10  Corea del Norte    91    120     235

In [ ]:
# Usando el loc extrae todas las columnas de la fila de Tailandia.

In [43]:
print(medallas.index)


RangeIndex(start=0, stop=10, step=1)


In [45]:
valor_tailandia = medallas.loc[6, :]
valor_tailandia

Unnamed: 0            7
País          Tailandia
Oro                 132
Plata               175
Bronce              278
Name: 6, dtype: object

In [47]:
# Usando el loc extrae todas las columnas de China e Irán.
valor_china_iran = medallas.loc[[0,3] , : ]
valor_china_iran

Unnamed: 0   País   Oro  Plata  Bronce
0           1  China  1473    994     720
3           4   Irán   179    181     197

In [ ]:
# Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

In [49]:
valor_china_iran = medallas.loc[[0,3], ["Oro", "Plata", "Bronce"] ]
valor_china_iran

Oro  Plata  Bronce
0  1473    994     720
3   179    181     197

In [ ]:
# Usando el iloc extrae la información de la India. Devolved todas las columnas.

In [51]:
infor_india = medallas.iloc[5, :]
infor_india

Unnamed: 0        6
País          India
Oro             154
Plata           202
Bronce          315
Name: 5, dtype: object

In [55]:
# Usando el iloc extrae todas las columnas de los paises que estén en posición impar. 
# La primera que nos tendría que salir es Japón y la última Corea del Norte.

impar = medallas.iloc[1:10:2]
impar

Unnamed: 0             País   Oro  Plata  Bronce
1           2            Japón  1032   1037     985
3           4             Irán   179    181     197
5           6            India   154    202     315
7           8        Indonesia   112    131     240
9          10  Corea del Norte    91    120     235

In [60]:
# Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

impar2 = medallas.iloc[1:10:2, 2:5]
impar2

Oro  Plata  Bronce
1  1032   1037     985
3   179    181     197
5   154    202     315
7   112    131     240
9    91    120     235

In [ ]:
# Contesta a las siguientes preguntas:
# ¿Qué país consiguió más de 200 medallas de oro?
oro = medallas[medallas["Oro"] > 200] 
oro



Unnamed: 0           País   Oro  Plata  Bronce
0           1          China  1473    994     720
1           2          Japón  1032   1037     985
2           3  Corea del Sur   745    663     827

In [64]:
# ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
oro_plata = medallas[(medallas["Oro"] > 200) & (medallas["Plata"] > 1000)]
oro_plata

Unnamed: 0   País   Oro  Plata  Bronce
1           2  Japón  1032   1037     985

In [ ]:
# ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?
oro_bronce = medallas[(medallas["Oro"] > 200) | (medallas["Bronce"] > 700)]
oro_bronce

Unnamed: 0           País   Oro  Plata  Bronce
0           1          China  1473    994     720
1           2          Japón  1032   1037     985
2           3  Corea del Sur   745    663     827

In [69]:
# Crea una nueva columma que se llame "total" que sea el resultado 
# de la suma de todas las medallas obtenidas por cada país.
medallas["total"] = medallas["Oro"] + medallas["Plata"] + medallas["Bronce"]
medallas

Unnamed: 0             País   Oro  Plata  Bronce  total
0           1            China  1473    994     720   3187
1           2            Japón  1032   1037     985   3054
2           3    Corea del Sur   745    663     827   2235
3           4             Irán   179    181     197    557
4           5       Kazajistán   155    158     224    537
5           6            India   154    202     315    671
6           7        Tailandia   132    175     278    585
7           8        Indonesia   112    131     240    483
8           9     China Taipéi    99    144     276    519
9          10  Corea del Norte    91    120     235    446